/**
 * pi system prompts generated by `scripts/generate-pi-prompt-fixtures.ts`
 * from an installed pi release and the extensions that rewrite its prompt,
 * one directory per prompt layout.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const PI_PROMPT_FIXTURES = join(import.meta.dir, "pi-prompts");

export interface PiPromptFixture {
	name: string;
	description: string;
	/** pi's prompt options. */
	input: Record<string, unknown>;
	next?: Record<string, unknown>;
	/** The system text as the adapters hand it to the bridge. */
	system: string;
	/** The system messages pi sends, in order; `system` is them joined by a blank line. */
	messages: string[];
	/** pi's own sections after every update; null for a forced prompt. */
	sections: Record<string, string> | null;
	expect:
		| {
				outcome: "forwarded";
				headStripped: boolean;
				/** The exact append, assembled from pi's own rendering. */
				forwarded: string | null;
				removedUpdates: number;
		  }
		| {
				outcome: "refused";
				code: string;
				reason: string;
				section: string | null;
		  };
}

export function loadPiPromptFixtures(version: string): PiPromptFixture[] {
	const dir = join(PI_PROMPT_FIXTURES, version);
	return readdirSync(dir)
		.filter((file) => file.endsWith(".json") && file !== "manifest.json")
		.sort()
		.map(
			(file) =>
				JSON.parse(readFileSync(join(dir, file), "utf8")) as PiPromptFixture,
		);
}

export function loadPiPromptFixture(
	version: string,
	name: string,
): PiPromptFixture {
	const found = loadPiPromptFixtures(version).find((f) => f.name === name);
	if (!found) throw new Error(`no pi ${version} fixture ${name}`);
	return found;
}

/** The append a forwarded fixture must produce. */
export function expectedAppend(f: PiPromptFixture): string | null {
	return f.expect.outcome === "forwarded" ? f.expect.forwarded : null;
}
