/**
 * pi system prompts generated by `scripts/generate-pi-prompt-fixtures.ts`
 * from an installed pi release, one directory per prompt layout.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const PI_PROMPT_FIXTURES = join(import.meta.dir, "pi-prompts");

export interface PiPromptFixture {
	name: string;
	description: string;
	/** pi's prompt options. */
	input: Record<string, unknown>;
	next?: Record<string, unknown>;
	/** The system text as the adapters hand it to the bridge. */
	system: string;
	/** The system messages pi sends, in order; `system` is them joined by a blank line. */
	messages: string[];
	/** pi's own sections after every update; null for a forced prompt. */
	sections: Record<string, string> | null;
	expect:
		| {
				outcome: "projected";
				shape: "stock" | "replaced" | "sectionless";
				droppedSections: string[];
				sectionUpdates: number;
		  }
		| {
				outcome: "refused";
				code: string;
				reason: string;
				section: string | null;
		  };
}

export function loadPiPromptFixtures(version: string): PiPromptFixture[] {
	const dir = join(PI_PROMPT_FIXTURES, version);
	return readdirSync(dir)
		.filter((file) => file.endsWith(".json") && file !== "manifest.json")
		.sort()
		.map(
			(file) =>
				JSON.parse(readFileSync(join(dir, file), "utf8")) as PiPromptFixture,
		);
}

/** The append a projected fixture must produce, built from pi's own sections. */
export function expectedAppend(f: PiPromptFixture): string | null {
	if (f.expect.outcome !== "projected") return null;
	if (f.expect.shape === "sectionless" || !f.sections) return f.system;
	const sections = f.sections;
	const kept = ["project_context", "skills", "addendum", "cwd"].flatMap(
		(name) => (sections[name] === undefined ? [] : [sections[name]]),
	);
	const parts =
		f.expect.shape === "replaced" ? [sections.preamble ?? "", ...kept] : kept;
	return parts.join("\n\n");
}
