#!/usr/bin/env bun
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// This script embeds the 3 SQLite maintenance workers (vacuum, integrity-check,
// incremental-vacuum) into gitignored `inline-*.ts` files that the database
// package imports at runtime. For each worker it:
//   1. writes an empty `EMBEDDED_*` placeholder if the inline file is missing,
//      so imports resolve while the worker source is bundled;
//   2. `bun build`s the worker source into a temporary dist dir;
//   3. base64-encodes the bundle;
//   4. overwrites the inline file with the real `EMBEDDED_*` constant.
//
// All paths are resolved from `import.meta.dir` (this script lives in
// `packages/database/scripts/`), so the script does not depend on process.cwd().

const HEADER =
	"// Auto-generated by `bun run build:db-workers` (packages/database/scripts/build-workers.ts). Do not edit manually.";

// packages/database/src — worker sources and inline outputs live here.
const srcDir = join(import.meta.dir, "../src");
// Intermediate `bun build` output dir. Kept in an OS temp dir so the bundle
// artifacts never land inside the tracked package tree.
const distDir = join(tmpdir(), "clankermux-db-workers");

interface Worker {
	/** Worker source filename (without dir), e.g. "vacuum-worker.ts". */
	source: string;
	/** Inline output filename (without dir), e.g. "inline-vacuum-worker.ts". */
	inline: string;
	/** Bundle filename written to distDir, e.g. "vacuum-worker.js". */
	bundle: string;
	/** Exported constant name, e.g. "EMBEDDED_VACUUM_WORKER_CODE". */
	constName: string;
}

const workers: Worker[] = [
	{
		source: "vacuum-worker.ts",
		inline: "inline-vacuum-worker.ts",
		bundle: "vacuum-worker.js",
		constName: "EMBEDDED_VACUUM_WORKER_CODE",
	},
	{
		source: "integrity-check-worker.ts",
		inline: "inline-integrity-check-worker.ts",
		bundle: "integrity-check-worker.js",
		constName: "EMBEDDED_INTEGRITY_CHECK_WORKER_CODE",
	},
	{
		source: "incremental-vacuum-worker.ts",
		inline: "inline-incremental-vacuum-worker.ts",
		bundle: "incremental-vacuum-worker.js",
		constName: "EMBEDDED_INCREMENTAL_VACUUM_WORKER_CODE",
	},
];

async function buildWorkers() {
	console.log("🔨 Building DB workers...");

	// 1. Write empty placeholders first (if missing) so the worker source imports
	//    of the inline files resolve during the `bun build` step below.
	for (const worker of workers) {
		const inlinePath = join(srcDir, worker.inline);
		if (!existsSync(inlinePath)) {
			writeFileSync(
				inlinePath,
				`${HEADER}\nexport const ${worker.constName} = "";`,
			);
		}
	}

	// Ensure the intermediate dist dir exists.
	mkdirSync(distDir, { recursive: true });

	// 2-4. For each worker: bundle → base64-encode → overwrite the inline file.
	for (const worker of workers) {
		const sourcePath = join(srcDir, worker.source);
		const bundlePath = join(distDir, worker.bundle);

		execSync(
			`bun build ${sourcePath} --outfile ${bundlePath} --target=bun --minify`,
			{ stdio: "inherit" },
		);

		const bundleCode = await Bun.file(bundlePath).text();
		const encoded = Buffer.from(bundleCode).toString("base64");

		const inlinePath = join(srcDir, worker.inline);
		writeFileSync(
			inlinePath,
			`${HEADER}\nexport const ${worker.constName} = "${encoded}";`,
		);
	}

	console.log("✅ Workers built and encoded\n");
}

buildWorkers().catch((error) => {
	console.error("Worker build failed:", error);
	process.exit(1);
});
