#!/usr/bin/env bun
import { execSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
	WORKERS,
	workerSrcDir,
	writeMissingWorkerPlaceholders,
} from "./workers-manifest.ts";

// This script embeds the workers listed in workers-manifest.ts into gitignored
// `inline-*.ts` files that their own package imports at runtime.
// For each worker it:
//   1. writes an empty `EMBEDDED_*` placeholder if the inline file is missing,
//      so imports resolve while the worker source is bundled;
//   2. `bun build`s the worker source into a temporary dist dir;
//   3. base64-encodes the bundle;
//   4. overwrites the inline file with the real `EMBEDDED_*` constant.
//
// Run with `--placeholders-only` to do step 1 and stop. That is what CI uses:
// `tsc` and `bun test` only need the exported symbols to resolve, so empty
// stubs are sufficient and skip the (much slower) bundling.

const HEADER =
	"// Auto-generated by `bun run build:db-workers` (packages/database/scripts/build-workers.ts). Do not edit manually.";

function writePlaceholders() {
	const written = writeMissingWorkerPlaceholders();
	const dirByInline = new Map(WORKERS.map((w) => [w.inline, w.dir]));
	for (const inline of written) {
		console.log(`wrote placeholder: ${dirByInline.get(inline)}/${inline}`);
	}
	const skipped = WORKERS.length - written.length;
	if (skipped > 0)
		console.log(`skipped ${skipped} already-present inline file(s)`);
}

async function buildWorkers() {
	console.log("🔨 Building DB workers...");

	// 1. Write empty placeholders first (if missing) so the worker source imports
	//    of the inline files resolve during the `bun build` step below.
	writeMissingWorkerPlaceholders();

	// Intermediate `bun build` output dir. In an OS temp dir so the bundle
	// artifacts never land inside the tracked package tree, and unique per
	// invocation: a fixed name is shared across checkouts, so two builds running
	// at once write the same bundle filenames and each can read the other's
	// output back into its inline file.
	const distDir = mkdtempSync(join(tmpdir(), "clankermux-db-workers-"));

	try {
		// 2-4. For each worker: bundle → base64-encode → overwrite the inline file.
		for (const worker of WORKERS) {
			const sourcePath = join(workerSrcDir(worker), worker.source);
			const bundlePath = join(distDir, worker.bundle);

			execSync(
				`bun build ${sourcePath} --outfile ${bundlePath} --target=bun --minify`,
				{ stdio: "inherit" },
			);

			const bundleCode = await Bun.file(bundlePath).text();
			const encoded = Buffer.from(bundleCode).toString("base64");

			const inlinePath = join(workerSrcDir(worker), worker.inline);
			writeFileSync(
				inlinePath,
				`${HEADER}\nexport const ${worker.constName} = "${encoded}";`,
			);
		}
	} finally {
		rmSync(distDir, { recursive: true, force: true });
	}

	console.log("✅ Workers built and encoded\n");
}

if (process.argv.includes("--placeholders-only")) {
	writePlaceholders();
} else {
	buildWorkers().catch((error) => {
		console.error("Worker build failed:", error);
		process.exit(1);
	});
}
