/**
 * workers-manifest.ts — the single source of truth for the SQLite workers that
 * `bun run build:db-workers` embeds into gitignored `inline-*.ts` files.
 *
 * Three consumers derive from this list, and they must never drift apart:
 *   - build-workers.ts        — bundles + base64-encodes each worker;
 *   - build-workers.ts --placeholders-only — the CI step that writes empty
 *     stubs so `bun test` can resolve the imports without a full build;
 *   - scripts/guarded-build.ts — decides whether the db-workers build is stale.
 *
 * Adding a worker here is the only edit required to keep all three correct.
 * (Adding one to a hand-maintained copy of this list is what broke CI for the
 * payload-write worker: `bun test` failed to load 70 test files with
 * `Cannot find module './inline-payload-write-worker'`.)
 */
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface Worker {
	/** Worker source filename (without dir), e.g. "vacuum-worker.ts". */
	source: string;
	/** Inline output filename (without dir), e.g. "inline-vacuum-worker.ts". */
	inline: string;
	/** Bundle filename written to the temp dist dir, e.g. "vacuum-worker.js". */
	bundle: string;
	/** Exported constant name, e.g. "EMBEDDED_VACUUM_WORKER_CODE". */
	constName: string;
}

export const WORKERS: Worker[] = [
	{
		source: "vacuum-worker.ts",
		inline: "inline-vacuum-worker.ts",
		bundle: "vacuum-worker.js",
		constName: "EMBEDDED_VACUUM_WORKER_CODE",
	},
	{
		source: "integrity-check-worker.ts",
		inline: "inline-integrity-check-worker.ts",
		bundle: "integrity-check-worker.js",
		constName: "EMBEDDED_INTEGRITY_CHECK_WORKER_CODE",
	},
	{
		source: "incremental-vacuum-worker.ts",
		inline: "inline-incremental-vacuum-worker.ts",
		bundle: "incremental-vacuum-worker.js",
		constName: "EMBEDDED_INCREMENTAL_VACUUM_WORKER_CODE",
	},
	{
		source: "payload-write-worker.ts",
		inline: "inline-payload-write-worker.ts",
		bundle: "payload-write-worker.js",
		constName: "EMBEDDED_PAYLOAD_WRITE_WORKER_CODE",
	},
];

/**
 * packages/database/src — worker sources and inline outputs live here. Resolved
 * from `import.meta.dir` (this module lives in `packages/database/scripts/`),
 * so it does not depend on process.cwd().
 */
export const WORKER_SRC_DIR = join(import.meta.dir, "../src");

/** Repo-root-relative paths of the inline outputs, for build-hash guards. */
export const WORKER_INLINE_REPO_PATHS = WORKERS.map(
	(worker) => `packages/database/src/${worker.inline}`,
);

const HEADER =
	"// Auto-generated by `bun run build:db-workers` (packages/database/scripts/build-workers.ts). Do not edit manually.";

/**
 * Write an empty `EMBEDDED_* = ""` stub for every worker whose inline file is
 * missing, so `import`s of it resolve. Existing files are left alone — never
 * clobber a real, built bundle.
 *
 * Two callers, for the same reason (imports must resolve before the code that
 * needs them runs): build-workers.ts, before bundling each worker source; and
 * CI, before `tsc` / `bun test`, which have no built bundles at all.
 *
 * @returns the inline filenames that were written.
 */
export function writeMissingWorkerPlaceholders(): string[] {
	const written: string[] = [];
	for (const worker of WORKERS) {
		const inlinePath = join(WORKER_SRC_DIR, worker.inline);
		if (existsSync(inlinePath)) continue;
		writeFileSync(
			inlinePath,
			`${HEADER}\nexport const ${worker.constName} = "";\n`,
		);
		written.push(worker.inline);
	}
	return written;
}
