/**
 * Section scoping for GET /api/analytics.
 *
 * Three things are under test:
 *  1. The unscoped path still emits the pre-sections wire response, checked
 *     against a golden fixture captured BEFORE section scoping existed
 *     (__fixtures__/analytics-unscoped-golden.json). Comparing "no sections"
 *     against "all sections explicitly" would only prove the two new code paths
 *     agree with each other.
 *  2. A section list yields exactly those fields — omitted, never zero-filled —
 *     with meta.sections echoing the RESOLVED set including implied deps.
 *  3. The conditional additional-data UNION keeps its branch-LOCAL bind order.
 *     Those cases run with a BOUNDED range and non-empty account/model/key/
 *     project filters: with `range=all` and no filters `queryParams` is empty,
 *     and every possible bind-order bug would pass unnoticed.
 */
import { Database } from "bun:sqlite";
import {
	afterEach,
	beforeEach,
	describe,
	expect,
	it,
	setSystemTime,
} from "bun:test";
import { BunSqlAdapter, ensureSchema } from "@clankermux/database";
import { ANALYTICS_SECTIONS, type AnalyticsSection } from "@clankermux/types";
import type { AnalyticsResponse, APIContext } from "../../types";
import { createAnalyticsHandler } from "../analytics-direct";
import { createIsolatedAnalyticsHandler } from "../analytics-runner";
import GOLDEN from "./__fixtures__/analytics-unscoped-golden.json";
import {
	ACCOUNT_A,
	ACCOUNT_B,
	API_KEY_DELETED,
	API_KEY_LIVE,
	API_KEY_RENAMED,
	API_KEY_RENAMED_NAME,
	FIXED_NOW,
	PROJECT_ALPHA,
	PROJECT_BETA,
	seedAnalyticsFixture,
} from "./analytics-section-fixture";

let db: Database;
let context: APIContext;

beforeEach(() => {
	// The handler reads Date.now() for the burn-rate windows and the range
	// cutoff; freezing it is what makes the golden comparison exact.
	setSystemTime(new Date(FIXED_NOW));
	db = new Database(":memory:");
	ensureSchema(db);
	seedAnalyticsFixture(db);
	const adapter = new BunSqlAdapter(db);
	context = {
		db: adapter,
		config: {},
		dbOps: { getAdapter: () => adapter },
	} as unknown as APIContext;
});

afterEach(() => {
	db.close();
	setSystemTime();
});

async function fetchAnalytics(query: string): Promise<{
	status: number;
	body: AnalyticsResponse & { error?: string };
}> {
	const response = await createAnalyticsHandler(context)(
		new URLSearchParams(query),
	);
	return { status: response.status, body: await response.json() };
}

/** All top-level fields the unscoped response carries. */
const FULL_FIELDS = Object.keys(GOLDEN) as Array<keyof AnalyticsResponse>;

describe("unscoped analytics response (backward compatibility)", () => {
	it("matches the pre-sections golden fixture field for field", async () => {
		const { status, body } = await fetchAnalytics("range=all");
		expect(status).toBe(200);

		// meta.sections is additive and is asserted separately below, so it is
		// stripped from BOTH sides: the golden is regenerated by
		// scripts/generate-analytics-golden.ts, which emits the field, and
		// comparing it would only restate the assertion that follows. Everything
		// else must match the captured response field for field.
		const { sections, ...meta } = body.meta ?? {};
		const { sections: _goldenSections, ...goldenMeta } = (
			GOLDEN as unknown as AnalyticsResponse
		).meta as NonNullable<AnalyticsResponse["meta"]>;
		expect({ ...body, meta }).toEqual({
			...(GOLDEN as unknown as AnalyticsResponse),
			meta: goldenMeta,
		});
		expect(sections).toEqual([...ANALYTICS_SECTIONS].sort());
	});

	it("still emits every field when every section is requested explicitly", async () => {
		const { body } = await fetchAnalytics(
			`range=all&sections=${ANALYTICS_SECTIONS.join(",")}`,
		);
		for (const field of FULL_FIELDS) {
			expect(body[field]).toBeDefined();
		}
	});
});

describe("section scoping", () => {
	it("emits exactly the requested sections and omits the rest", async () => {
		const { body } = await fetchAnalytics(
			"range=all&sections=timeSeries,modelDistribution",
		);
		expect(body.timeSeries).toBeDefined();
		expect(body.modelDistribution).toBeDefined();

		for (const field of FULL_FIELDS) {
			if (field === "meta" || field === "timeSeries") continue;
			if (field === "modelDistribution") continue;
			// Omitted, NEVER zero-filled: absence is the signal the caller uses to
			// tell "not requested" from "no data in range".
			expect(body).not.toHaveProperty(field);
		}
	});

	it("echoes the RESOLVED section set in meta.sections", async () => {
		const { body } = await fetchAnalytics(
			"range=all&sections=contextComposition",
		);
		// contextComposition implies totals.
		expect(body.meta?.sections).toEqual(["contextComposition", "totals"]);
	});

	it("canonicalizes order and duplicates to one section set", async () => {
		const forward = await fetchAnalytics(
			"range=all&sections=timeSeries,modelDistribution",
		);
		const shuffled = await fetchAnalytics(
			"range=all&sections=modelDistribution,timeSeries,modelDistribution",
		);
		expect(shuffled.body.meta?.sections).toEqual(forward.body.meta?.sections);
		expect(shuffled.body).toEqual(forward.body);
	});
});

describe("implied section dependencies", () => {
	it("contextComposition alone still yields a correct coverage.totalRequests", async () => {
		const { body } = await fetchAnalytics(
			"range=all&sections=contextComposition",
		);
		expect(body.contextComposition).toBeDefined();
		// The consolidated totals query is what supplies this denominator, which
		// is exactly why contextComposition implies totals.
		expect(body.contextComposition?.coverage.totalRequests).toBe(
			GOLDEN.contextComposition.coverage.totalRequests,
		);
		expect(body.totals?.requests).toBe(GOLDEN.totals.requests);
	});

	it("speedTotals alone yields a totals object carrying the percentiles", async () => {
		const { body } = await fetchAnalytics("range=all&sections=speedTotals");
		expect(body.meta?.sections).toEqual(["speedTotals", "totals"]);
		expect(body.totals?.medianTokensPerSecond).toBe(
			GOLDEN.totals.medianTokensPerSecond,
		);
		expect(body.totals?.p95TokensPerSecond).toBe(
			GOLDEN.totals.p95TokensPerSecond,
		);
	});

	it("omits the speed percentiles from totals when speedTotals was not requested", async () => {
		const { body } = await fetchAnalytics("range=all&sections=totals");
		expect(body.totals).toBeDefined();
		expect(body.totals).not.toHaveProperty("medianTokensPerSecond");
		expect(body.totals).not.toHaveProperty("p95TokensPerSecond");
	});

	it("activeSessionsByAccount alone still yields timeSeries and the total", async () => {
		const { body } = await fetchAnalytics(
			"range=all&sections=activeSessionsByAccount",
		);
		expect(body.meta?.sections).toEqual([
			"activeSessions",
			"activeSessionsByAccount",
		]);
		expect(body.activeSessions?.totalDistinctSessions).toBe(
			GOLDEN.activeSessions.totalDistinctSessions,
		);
		expect(body.activeSessions?.timeSeries).toEqual(
			GOLDEN.activeSessions.timeSeries as never,
		);
		expect(body.activeSessions?.perAccount).toBeDefined();
	});

	it("omits perAccount when only activeSessions was requested", async () => {
		const { body } = await fetchAnalytics("range=all&sections=activeSessions");
		expect(body.activeSessions).toBeDefined();
		expect(body.activeSessions).not.toHaveProperty("perAccount");
	});
});

describe("sections validation", () => {
	it("rejects an unknown section by name with 400", async () => {
		const { status, body } = await fetchAnalytics(
			"range=all&sections=totals,bogusSection",
		);
		expect(status).toBe(400);
		expect(body.error).toContain("bogusSection");
	});

	it("rejects a present-but-empty sections param with 400", async () => {
		const { status } = await fetchAnalytics("range=all&sections=");
		expect(status).toBe(400);
	});

	it("validates on the main thread, before any worker dispatch", async () => {
		// A db path present means the runner would normally hand the request to
		// the worker. A bad section must still 400 immediately rather than
		// queueing behind a slow heavy query and returning a 503 soft timeout.
		const workerContext = {
			db: context.db,
			config: {},
			dbOps: {
				getAdapter: context.dbOps.getAdapter,
				// Nonexistent path: if the request reached the worker it would fail
				// with a 500/503, not a 400.
				getResolvedDbPath: () => "/nonexistent/clankermux-sections-test.db",
			},
		} as unknown as APIContext;

		const response = await createIsolatedAnalyticsHandler(workerContext)(
			new URLSearchParams("range=all&sections=nope"),
		);
		expect(response.status).toBe(400);
	});
});

/**
 * Bounded range + non-empty filters on every filterable dimension, so
 * `queryParams` is long and a shifted bind is guaranteed to change results.
 */
const FILTERED_QUERY =
	`range=30d` +
	`&accounts=${ACCOUNT_A},${ACCOUNT_B}` +
	`&models=claude-opus-4-8,claude-sonnet-5` +
	`&apiKeys=${API_KEY_LIVE},${API_KEY_RENAMED}` +
	`&projects=${PROJECT_ALPHA},${PROJECT_BETA}`;

const UNION_SECTIONS: AnalyticsSection[] = [
	"modelDistribution",
	"accountPerformance",
	"costByModel",
	"apiKeyPerformance",
	"accountModelUsage",
	"projectBreakdown",
];

describe("conditional additional-data UNION (branch-local bind order)", () => {
	it("the filtered fixture actually exercises the filters", async () => {
		// Guard the guard: if the filters matched everything (or nothing) the
		// bind-order cases below would be vacuous.
		const all = await fetchAnalytics("range=30d&sections=totals");
		const filtered = await fetchAnalytics(`${FILTERED_QUERY}&sections=totals`);
		expect(filtered.body.totals?.requests).toBeGreaterThan(0);
		expect(filtered.body.totals?.requests).toBeLessThan(
			all.body.totals?.requests ?? 0,
		);
	});

	it.each(
		UNION_SECTIONS,
	)("branch '%s' alone returns the same rows as the full UNION", async (section) => {
		const full = await fetchAnalytics(
			`${FILTERED_QUERY}&sections=${UNION_SECTIONS.join(",")}`,
		);
		const alone = await fetchAnalytics(`${FILTERED_QUERY}&sections=${section}`);
		expect(alone.body[section]).toEqual(full.body[section] as never);
	});

	it("the Overview subset returns the same rows as the full request", async () => {
		const overviewSections =
			"totals,timeSeries,modelDistribution,apiKeyModelUsage,projectBreakdown,activeSessions";
		const subset = await fetchAnalytics(
			`${FILTERED_QUERY}&sections=${overviewSections}`,
		);
		const full = await fetchAnalytics(FILTERED_QUERY);

		expect(subset.body.modelDistribution).toEqual(
			full.body.modelDistribution as never,
		);
		// Not a UNION branch (its rows need three columns where the shared shape
		// carries two), so this is the standalone phase answering the same way
		// inside a subset as it does in the full response.
		expect(subset.body.apiKeyModelUsage).toEqual(
			full.body.apiKeyModelUsage as never,
		);
		expect(subset.body.projectBreakdown).toEqual(
			full.body.projectBreakdown as never,
		);
		// The Overview list omits `speedTotals`, so its totals carry no speed
		// percentiles; every other total must agree with the full response.
		const {
			medianTokensPerSecond: _median,
			p95TokensPerSecond: _p95,
			...fullTotals
		} = full.body.totals ?? {};
		expect(subset.body.totals).toEqual(fullTotals as never);
	});

	it("projectBreakdown alone still emits the untruncated no-project bucket", async () => {
		// Unfiltered on project so the NULL bucket is in scope.
		const { body } = await fetchAnalytics(
			"range=all&sections=projectBreakdown",
		);
		const rows = body.projectBreakdown ?? [];
		expect(rows.some((row) => row.project === null)).toBe(true);
		expect(rows).toEqual(GOLDEN.projectBreakdown as never);
	});

	it("skips the UNION query entirely when no branch is requested", async () => {
		const { body } = await fetchAnalytics("range=all&sections=totals");
		for (const section of UNION_SECTIONS) {
			expect(body).not.toHaveProperty(section);
		}
	});
});

/**
 * `apiKeyModelUsage` — the Overview's "Usage by API key" donut.
 *
 * The section's whole difficulty is that a display name is not an identity. A
 * key can be renamed, hard-deleted (leaving only whatever snapshot name each
 * request row happened to carry), and two different keys can end up wearing the
 * same string — including "No key", which is both the label for requests that
 * carried no key at all and a name a user is free to give a real one. Every
 * case below is one way that confusion would reach the donut as a slice whose
 * number belongs to nobody.
 */
describe("apiKeyModelUsage", () => {
	it("gives a hard-deleted key ONE label across its differing snapshot names", async () => {
		// The fixture's deleted key carries "retired-key" on one request row and
		// "retired-key-older" on another. Grouping is on the id, so both rows come
		// back under one identity and one label.
		const { body } = await fetchAnalytics(
			"range=all&sections=apiKeyModelUsage",
		);
		const rows = (body.apiKeyModelUsage ?? []).filter(
			(row) => row.apiKeyId === API_KEY_DELETED,
		);
		expect(rows.length).toBe(2);
		expect(new Set(rows.map((row) => row.apiKey)).size).toBe(1);
		expect(new Set(rows.map((row) => row.model)).size).toBe(2);
	});

	it("labels a renamed key with its CURRENT name, not the stamped snapshot", async () => {
		const { body } = await fetchAnalytics(
			"range=all&sections=apiKeyModelUsage",
		);
		const rows = (body.apiKeyModelUsage ?? []).filter(
			(row) => row.apiKeyId === API_KEY_RENAMED,
		);
		expect(rows.length).toBeGreaterThan(0);
		for (const row of rows) {
			expect(row.apiKey).toBe(API_KEY_RENAMED_NAME);
		}
	});

	it("reports the no-key bucket as apiKeyId null labelled 'No key'", async () => {
		const { body } = await fetchAnalytics(
			"range=all&sections=apiKeyModelUsage",
		);
		const rows = (body.apiKeyModelUsage ?? []).filter(
			(row) => row.apiKeyId === null,
		);
		expect(rows.length).toBeGreaterThan(0);
		for (const row of rows) {
			expect(row.apiKey).toBe("No key");
		}
	});

	it("puts a row with no model under 'Unknown' rather than dropping it", async () => {
		// Dropping null-model rows would make the per-key sums disagree with the
		// request count shown beside the donut. ~1.2% of live rows over 7 days.
		const { body } = await fetchAnalytics(
			"range=all&sections=apiKeyModelUsage",
		);
		expect(
			(body.apiKeyModelUsage ?? []).some((row) => row.model === "Unknown"),
		).toBe(true);
	});

	it("reconciles with totals.requests under the same filters", async () => {
		// No row cap and no null-model exclusion, so the slices add up to the
		// number the rest of the page reports for the same selection.
		const { body } = await fetchAnalytics(
			`${FILTERED_QUERY}&sections=totals,apiKeyModelUsage`,
		);
		const sum = (body.apiKeyModelUsage ?? []).reduce(
			(total, row) => total + row.count,
			0,
		);
		expect(sum).toBeGreaterThan(0);
		expect(sum).toBe(body.totals?.requests ?? -1);
	});

	it("is omitted, not zero-filled, when it was not requested", async () => {
		const { body } = await fetchAnalytics("range=all&sections=totals");
		expect(body).not.toHaveProperty("apiKeyModelUsage");
	});
});

/**
 * Identity cases the shared fixture cannot carry.
 *
 * These need rows the golden-fixture dataset deliberately does not have —
 * adding them there would change every other section's captured response — so
 * each runs against its own throwaway database.
 */
describe("apiKeyModelUsage identity edge cases", () => {
	function seedKeyUsage(
		keys: Array<{ id: string; name: string }>,
		requests: Array<{
			id: string;
			apiKeyId: string | null;
			apiKeyName: string | null;
			model: string | null;
		}>,
	): APIContext {
		const edgeDb = new Database(":memory:");
		ensureSchema(edgeDb);
		for (const key of keys) {
			edgeDb.run(
				`INSERT INTO api_keys (id, name, hashed_key, prefix_last_8, created_at, last_used, usage_count, is_active)
				 VALUES (?, ?, ?, ?, ?, NULL, 0, 1)`,
				[key.id, key.name, `hash-${key.id}`, key.id.slice(-8), FIXED_NOW],
			);
		}
		const insert = edgeDb.prepare(
			`INSERT INTO requests
				(id, timestamp, method, path, account_used, status_code, success,
				 error_message, response_time_ms, failover_attempts, model,
				 api_key_id, api_key_name)
			 VALUES (?, ?, 'POST', '/v1/messages', NULL, 200, 1, NULL, 100, 0, ?, ?, ?)`,
		);
		for (const request of requests) {
			insert.run(
				request.id,
				FIXED_NOW - 60_000,
				request.model,
				request.apiKeyId,
				request.apiKeyName,
			);
		}
		const adapter = new BunSqlAdapter(edgeDb);
		return {
			db: adapter,
			config: {},
			dbOps: { getAdapter: () => adapter },
		} as unknown as APIContext;
	}

	async function readUsage(edgeContext: APIContext) {
		const response = await createAnalyticsHandler(edgeContext)(
			new URLSearchParams("range=all&sections=apiKeyModelUsage"),
		);
		const body = (await response.json()) as AnalyticsResponse;
		return body.apiKeyModelUsage ?? [];
	}

	it("keeps two ids apart when they wear the same display name", async () => {
		// A hard-deleted key's snapshot name can equal a live key's current name.
		// They are different keys; merging them would report one number for two.
		const rows = await readUsage(
			seedKeyUsage(
				[{ id: "k-live", name: "shared-name" }],
				[
					{
						id: "q-1",
						apiKeyId: "k-live",
						apiKeyName: "shared-name",
						model: "opus",
					},
					{
						id: "q-2",
						apiKeyId: "k-gone",
						apiKeyName: "shared-name",
						model: "opus",
					},
				],
			),
		);

		expect(rows).toHaveLength(2);
		expect(rows.every((row) => row.apiKey === "shared-name")).toBe(true);
		expect(new Set(rows.map((row) => row.apiKeyId))).toEqual(
			new Set(["k-live", "k-gone"]),
		);
	});

	it("keeps a real key named 'No key' apart from the no-key bucket", async () => {
		// The bucket's label is a label. The identity is the id, and null is not
		// a name anyone can take.
		const rows = await readUsage(
			seedKeyUsage(
				[{ id: "k-named", name: "No key" }],
				[
					{
						id: "q-1",
						apiKeyId: "k-named",
						apiKeyName: "No key",
						model: "opus",
					},
					{ id: "q-2", apiKeyId: null, apiKeyName: null, model: "opus" },
				],
			),
		);

		expect(rows).toHaveLength(2);
		expect(rows.every((row) => row.apiKey === "No key")).toBe(true);
		expect(rows.filter((row) => row.apiKeyId === null)).toHaveLength(1);
		expect(rows.filter((row) => row.apiKeyId === "k-named")).toHaveLength(1);
	});

	it("returns every (key, model) pair — there is no row cap", async () => {
		// A LIMIT would silently stop the slices summing to the request count
		// beside them, and the cut would land on the smallest keys, which is
		// exactly where an unexpected caller shows up.
		const keys = Array.from({ length: 12 }, (_, i) => ({
			id: `k-${i}`,
			name: `key-${i}`,
		}));
		const requests = keys.flatMap((key, i) =>
			Array.from({ length: 5 }, (_, m) => ({
				id: `q-${i}-${m}`,
				apiKeyId: key.id,
				apiKeyName: key.name,
				model: `model-${m}`,
			})),
		);

		const rows = await readUsage(seedKeyUsage(keys, requests));

		expect(rows).toHaveLength(60);
		expect(rows.reduce((total, row) => total + row.count, 0)).toBe(60);
	});
});
