import { PUBLIC_ACCOUNTS_SCHEMA, PUBLIC_STATUS_SCHEMA, PUBLIC_STOPS_SCHEMA, PUBLIC_STREAM_SCHEMA } from "../../packages/http-api/src/handlers/public/dto";
import { PUBLIC_WORKLOADS_SCHEMA } from "../../packages/http-api/src/handlers/public/workloads-dto";
export const resources = {
 status:{type:"PublicStatusDto",id:PUBLIC_STATUS_SCHEMA},
 accounts:{type:"PublicAccountsDto",id:PUBLIC_ACCOUNTS_SCHEMA},
 workloads:{type:"PublicWorkloadsDto",id:PUBLIC_WORKLOADS_SCHEMA},
 stops:{type:"PublicStopsDto",id:PUBLIC_STOPS_SCHEMA},
 stream:{type:"PublicStreamEventDto",id:PUBLIC_STREAM_SCHEMA},
} as const;
export type PublicResource=keyof typeof resources;

/** Count names whose spelling does not already end in Count. */
export const countFields = new Set([
	"configured",
	"defaultRoutable",
	"paused",
	"rateLimited",
	"usageExhausted",
	"totalRequests",
	"blockedRequests",
	"failedRequests",
	"disconnectedRequests",
	"unclassifiedRequests",
	"excludedAttemptAuditRows",
	"observedRequests",
	"zeroCandidateRequests",
	"requests",
	"count",
	"eligibleTotal",
	"willRunOut",
	"alreadySpent",
	"learning",
	"unstarted",
	"fiveHourRoom",
	"fiveHourRunningHot",
	"fiveHourWaiting",
	"fiveHourUnavailable",
	"fiveHourUnknown",
	"eligibleAccounts",
"modeledAccounts",
"idleAccounts",
"unavailableAccounts",
"availableAccounts",
"constrainedAccounts",
"unknownAccounts",
"atRiskAccounts",
"withinBudgetAccounts",
	"unreadableAccounts",
	"unopenedAccounts",
	"learningAccounts",
	"spentAccounts",
	"failoverAttempts",
	"totalTokens",
]);
